### ISSUE TITLE
Client: The action buttons don't scroll with the messages

### ISSUE THREAD

**Issue by IoIxD** [itsmattkc/kcchat-server#2]
I'm aware this repo is for the server but there's no public repo for the client so I see no choice but to make it here.

The action buttons don't scroll with the messages. When you scroll up, the action buttons don't, and can be unusable.

![image](https://user-images.githubusercontent.com/30945097/216176554-de63dad2-ee3f-4f49-9531-7c3542eccda3.png)
![image](https://user-images.githubusercontent.com/30945097/216176596-120fef12-a5b8-453b-ab2b-6377835eaa94.png)

**Comment by itsmattkc** [comment]
Who thought CSS was a good idea?

Fixed now.
